const HTTP_NOT_FOUND = 404;
const INVALID_DATA_ERROR = 400;
const DEFAULT_ERROR = 500;
const DB_ERROR = 11000;
const CONFLICT_ERROR = 409;
const AUTHORIZATION_ERROR = 401;
const FORBIDDEN_ERROR = 403;

module.exports = {
  HTTP_NOT_FOUND,
  INVALID_DATA_ERROR,
  DEFAULT_ERROR,
  CONFLICT_ERROR,
  AUTHORIZATION_ERROR,
  FORBIDDEN_ERROR,
  DB_ERROR,
};
